version: 2

plan:
  project-key: WINK
  key: PYPI
  name: PyPI Release Pipeline

stages:
  - stage:
      - SDK Generation
        - Generate
      - Github release
        - Release
      - PyPI release
        - PyPI

Generate:      
  tasks:
    - checkout
    - script:
        interpreter: /bin/bash
        scripts:
          - chmod +x generateSDKsFromOpenAPISpecs.sh
          - ./generateSDKsFromOpenAPISpecs.sh production
    - script:
        interpreter: /bin/bash
        scripts:
          - git add .
          - git commit -m "chore: update SDKs for version $(cat VERSION)" || echo "No changes to commit."
          - git push origin develop

Release:
  tasks:
    - checkout
    - script:
        interpreter: /bin/bash
        scripts:
          - chmod +x release.sh
          - ./release.sh

PyPI:
  tasks:
    - checkout
    - script:
        interpreter: /bin/bash
        scripts:
          - chmod +x pypi-release.sh
          - ./pypi-release.sh